version: "3"

services:
    nginx:
        build: nginx
        image: nginx_revproxy
        container_name: nginx_revproxy1
        volumes:
            - letsencrypt:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        environment:
            - CERTBOT_EMAIL=${CERTBOT_EMAIL}
            - CERTBOT_WEBROOT=${CERTBOT_WEBROOT}
            - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}

volumes:
    letsencrypt:
        external: true
