version: "3"

services:
    nginx:
        build: nginx
        image: nginx_revproxy
        container_name: nginx_revproxy1
        volumes:
            - letsencrypt:/etc/letsencrypt
        depends_on:
            - web1
            - web2
        ports:
            - "80:80"
            - "443:443"
        environment:
            - CERTBOT_EMAIL=${CERTBOT_EMAIL}
            - CERTBOT_WEBROOT=${CERTBOT_WEBROOT}
            - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}

    web1:
        build: web1
        image: nginx_web
        container_name: nginx_web1

    web2:
        build: web2
        image: apache_web
        container_name: apache_web1

volumes:
    letsencrypt:
        external: true
