version: "3"

services:
    revproxy:
        build: revproxy
        image: nginx_rp
        container_name: nginx_rp1
        volumes:
            - /srv/docker_volumes/letsencrypt:/etc/letsencrypt
        depends_on:
            - web1
            - web2
        ports:
            - "80:80"
            - "443:443"
        environment:
            - CERTBOT_EMAIL=${CERTBOT_EMAIL}
            - CERTBOT_WEBROOT=${CERTBOT_WEBROOT}
            - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}

    web1:
        build: web1
        image: nginx_web
        container_name: nginx_web1

    web2:
        build: web2
        image: apache_web
        container_name: apache_web1
