version: "3"

services:
    revproxy:
        build:
            context: revproxy
            args:
                - NGINX_VERSION=1.13.7-alpine
        image: nginx_rp
        container_name: nginx_rp1
        volumes:
            - /srv/docker_volumes/letsencrypt:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_DOMAIN=${CERTBOT_DOMAIN}
        depends_on:
            - web1
            - web2
        restart: unless-stopped

    web1:
        build:
            context: web1
            args:
                - NGINX_VERSION=1.13.7-alpine
        image: nginx_web
        container_name: nginx_web1

    web2:
        build:
            context: web2
            args:
                - APACHE_VERSION=2.4.29-alpine
        image: apache_web
        container_name: apache_web1
